title: "Ha Do â€” Data Analyst "
description: "Production-like data engineering builds, explained clearly."
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Ha Do"
github_username: "HaDo1802"
exclude:
  - "README.md"
